version: "3.8"

services:
  web:
    build: .
    image: web
    container_name: web
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - "4173"
    environment:
      - VIRTUAL_HOST=fysite.id
      - LETSENCRYPT_HOST=fysite.id
      - LETSENCRYPT_EMAIL=testedprojected@gmail.com
    volumes:
      - "/root/cms/content:/app/content"
      - "/root/cms/public:/app/public"

networks:
  nginx-proxy:
    external: true
