services:
  web:
    build: .
    image: web
    container_name: web
    restart: unless-stopped
    networks:
      - nginx-proxy
    expose:
      - "4173"
    env_file:
      - .env

networks:
  nginx-proxy:
    external: true
