name: Deploy web

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04-lts

    env:
      HOST: ${{ secrets.HOST }}
      USER: ${{ secrets.USER }}
      PASS: ${{ secrets.PASS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Connect to vps
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PASS }}
          script: |
            cd $HOME/web

            git reset --hard
            git clean -fd
            git pull origin main

            docker-compose down
            docker-compose up -d --build
            docker-compose ps
